
// This code is autogenerated, check generateAst.ts

export abstract class Expr {};

    
export class Binary extends Expr {
      constructor(public left: Expr, public operator: Token, public right: Expr) {}
    }
export class Grouping extends Expr {
      constructor(public expression: Expr) {}
    }
export class Literal extends Expr {
      constructor(public value: Object) {}
    }
export class Unary extends Expr {
      constructor(public operator: Token, public right: Expr) {}
    }
