
// This code is autogenerated, check generateAst.ts


import { Token } from '../src/Token';
export interface Visitor<R> {
	visitAssignExpr(expr: Assign): R
	visitBinaryExpr(expr: Binary): R
	visitGroupingExpr(expr: Grouping): R
	visitLiteralExpr(expr: Literal): R
	visitUnaryExpr(expr: Unary): R
	visitVariableExpr(expr: Variable): R
}

export abstract class Expr {
  abstract accept<R>(visitor: Visitor<R>): R;
};

    
export class Assign extends Expr {
      constructor(public name: Token, public value: Expr) {
        super();
      };

  accept<R>(visitor: Visitor<R>): R {
    return visitor.visitAssignExpr(this);
  }

}
export class Binary extends Expr {
      constructor(public left: Expr, public operator: Token, public right: Expr) {
        super();
      };

  accept<R>(visitor: Visitor<R>): R {
    return visitor.visitBinaryExpr(this);
  }

}
export class Grouping extends Expr {
      constructor(public expression: Expr) {
        super();
      };

  accept<R>(visitor: Visitor<R>): R {
    return visitor.visitGroupingExpr(this);
  }

}
export class Literal extends Expr {
      constructor(public value: any) {
        super();
      };

  accept<R>(visitor: Visitor<R>): R {
    return visitor.visitLiteralExpr(this);
  }

}
export class Unary extends Expr {
      constructor(public operator: Token, public right: Expr) {
        super();
      };

  accept<R>(visitor: Visitor<R>): R {
    return visitor.visitUnaryExpr(this);
  }

}
export class Variable extends Expr {
      constructor(public name: Token) {
        super();
      };

  accept<R>(visitor: Visitor<R>): R {
    return visitor.visitVariableExpr(this);
  }

}
